f = open("Anju.txt", 'w')
f.write("Hello anju...\nHope you are doing good")
f.close()
f = open("Anju.txt", 'r')
c = f.read()
print(c)
f.close()
f = open("Akash.txt", 'a')
f.write(c)
f.close()
f = open("Akash.txt", 'r+')
print(f.read())
f.close()